### PR TITLE
Include action to deploy kubeflow pipeline. 

### PR DESCRIPTION
**Pull request by NikeNano**
I have previously had discussions with @hamelsmu  and the kubeflow community about building a github action to compile and deploy a Kubeflow pipeline to Kubeflow. I have done some initial work on creating such an action. In order to help contribute it to the community and get some feedback I would be happy to contribute the action to the repo, the code is currently [here](https://github.com/NikeNano/kubeflow-github-action) I am happy to restructure according to the structure you like to have it in this repo? Just let me know :) 

The goal with the actions is to do the following:
1) Compile a kubeflow pipeline
2) Upload the pipeline to Kubeflow

Possible add on: 
3) Run the pipeline
4) Schedule the pipeline to run

I am new to github actions so super happy for all feedback. 

I have had issues with the kfp.Client and could not go around this: 

https://github.com/NikeNano/kubeflow-github-action/blob/85c441f3b2a8585ba1d378f2189391b058fc09cc/entrypoint.sh#L3

please let me know if you have some ideas!

### CODE REVIEW

**Comment by hamelsmu** [comment]
@NikeNano This is awesome.

We would gladly feature your Action in this repo, but first

-  I can help you put your  Action on the marketplace.  
- I can help fix any errors you are having

Maybe we pair and get that done?  Are you available for pair programming anytime next week?  Thanks

**Comment by NikeNano** [comment]
> @NikeNano This is awesome.
> 
> We would gladly feature your Action in this repo, but first
> 
> * I can help you put your  Action on the marketplace.
> * I can help fix any errors you are having
> 
> Maybe we pair and get that done? Are you available for pair programming anytime next week? Thanks

Sounds awesome! I answered on slack so lets keek the discussion there as you mentioned :)

**Comment by hamelsmu** [comment]
@NikeNano whats the status of this?

**Comment by NikeNano** [comment]
I am doing some last updates but, will be done tomorrow hopefully Had some things that I needed to solve at work. I remember you also asked about the cluster that it deploys to. My plan is to bring it down when down to avoid the cost, but you mentioned that there might be some other kubeflow cluster that we could use @hamelsmu?

**Comment by hamelsmu** [comment]
@jlewi do you have a GCP KF cluster @NikeNano  can use to test his KFP action?

**Comment by NikeNano** [comment]
@JohanWork would you like to review as well?

**Comment by JohanWork** [comment]
Looks like a really nice add, will go over it.

**Comment by NikeNano** [comment]
Thanks for the feedback in the separate PR @JohanWork!

**Comment by NikeNano** [comment]
@hamelsmu I am happy with the current state now :)

**Comment by hamelsmu** [comment]
@NikeNano if you are happy with it, please add a link to the README.  

> how should I add it/structure the code I like to add?

Can you explain what you mean by the above?  I am not sure.

**Comment by NikeNano** [comment]
> @NikeNano if you are happy with it, please add a link to the README.
> 
> > how should I add it/structure the code I like to add?
> 
> Can you explain what you mean by the above? I am not sure.

Ahhh you mean that I only add the link in the README and keep the source code separate in the current repo? My plan was to contribute the code as well to the repo and thus the question how I should do that. Hope it is more clear now :)

**Comment by hamelsmu** [comment]
Oh it’s actually a better idea to keep your action in a separate repo.  You only need to add the link to it here

**Comment by NikeNano** [comment]
Updated now, been a long day so will double check it tomorrow!

**Comment by hamelsmu** [comment]
@jlewi / @aronchick perhaps work with @NikeNano to write a Kubeflow blog post on his excellent contribution!

**Comment by NikeNano** [comment]
I will start to work on a blog post after I have made an example for the doc-sprint.  Would be great to do it together  @jlewi / @aronchick !

**Pull request merged**
