### PR TITLE
Changed Parameters of Model

### PR DESCRIPTION
**Pull request by hamelsmu**
I increased the size of the embeddings to give models more capacity to learn from the data
cc: @romanofoti

### CODE REVIEW

**Comment by romanofoti** [comment]
How did these changes to the code and parameters affect model performance?  It looks like you are ready for a final code review, so let's do a full test run and compare this against the baseline.  We can do this via GitHub Actions with this command:

/run-full-test

**Comment by hamelsmu** [comment]
/deploy 5mi2p6f1 foo bar

more noise

**Comment by hamelsmu** [comment]
/deploy 5mi2p6f1 foo bar wee

trying again @hohsiangwu

**Comment by hamelsmu** [comment]
/deploy 5mi2p6f1 foo bar wee

trying again @hohsiangwu maybe this time will be lucky

**Comment by hamelsmu** [comment]
/deploy 5mi2p6f1 aligators bar wee

trying again @hohsiangwu testing

**Comment by hamelsmu** [comment]
/deploy 5mi2p6f1 foo bar

bar baz

**Comment by hamelsmu** [comment]
/deploy 5mi2p6f1 lions tigers bears

bar baz

**Comment by hohsiangwu** [comment]
You can access the endpoint via `https://us-central1-github-probots.cloudfunctions.net/predict`

**Pull request closed without merging**
